### PR TITLE
Fixes inability to override spark conf; prefers spark-submit names

### LINKED ISSUE #29: Unable to pass sparkProperties to the job
It seems like we can not pass map properties (key-value pair) for [sparkProperties](https://github.com/openzipkin/zipkin-sparkstreaming/blob/master/sparkstreaming-job/src/main/java/zipkin/sparkstreaming/job/ZipkinSparkStreamingProperties.java#L25) to the job through command line. 

I was able to get it working by using a custom property parser, as suggested by [this stack overflow answer](http://stackoverflow.com/questions/28369458/how-to-fill-hashmap-from-java-property-file-with-spring-value). If there is no other way to do this, I can send a PR for this change.

I also tried [SPRING_APPLICATION_JSON](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config) as suggested by @shakuzen but could not get it working, even for a string property. Below is what I tried.

` $java -Dspring.application.json='{"zipkin.sparkstreaming.sparkMaster":"abc"}' -jar zipkin-sparkstreaming-job-0.1.1-SNAPSHOT.jar
`

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Before we couldn't override spark properties via CLI. This fixes that
and prefers spark-submit names for settings we provide.

Ex. the last property is the same as you'd pass to spark-submit, except
prefixed with `zipkin.sparkstreaming.conf`:
```bash
$ java -jar sparkstreaming-job/target//zipkin-sparkstreaming-job-0.1.1-SNAPSHOT.jar \
  --zipkin.storage.type=elasticsearch \
  --zipkin.storage.elasticsearch.hosts=http://127.0.0.1:9200 \
  --zipkin.sparkstreaming.stream.kafka.bootstrap-servers=127.0.0.1:9092 \
  --zipkin.sparkstreaming.conf.spark.eventLog.enabled=false
```

Fixes #29

### CODE REVIEW

**Comment by adriancole** [comment]
you can also test this by setting an invalid variable like below and watch it crash!

```
--zipkin.sparkstreaming.conf.spark.eventLog.enabled=faK1
```

File: sparkstreaming-job/src/main/java/zipkin/sparkstreaming/job/ZipkinSparkStreamingProperties.java [hunk 1]
```diff
@@ -13,41 +13,42 @@
...
 import java.util.Map;
 import org.springframework.boot.context.properties.ConfigurationProperties;
 import zipkin.sparkstreaming.SparkStreamingJob;
 
 @ConfigurationProperties("zipkin.sparkstreaming")
 public class ZipkinSparkStreamingProperties {
-  String sparkMaster;
-  List<String> sparkJars;
-  Map<String, String> sparkProperties;
+  String master;
```
Comment (mansu) [inline sparkstreaming-job/src/main/java/zipkin/sparkstreaming/job/ZipkinSparkStreamingProperties.java]: Would it make sense to make these fields public final and get rid of get and set methods?

Comment (adriancole) [inline sparkstreaming-job/src/main/java/zipkin/sparkstreaming/job/ZipkinSparkStreamingProperties.java]: I think the only it might make sense to do would be the properties (possibly the list), the non-collection fields would be unsettable if we made them final. cc @shakuzen

**Comment by naoman** [comment]
Thanks for the changes @adriancole. I tried it on our Spark cluster (running on Mesos) and it worked as expected.

**Comment by naoman** [comment]
@adriancole is it okay if I delete fix-property-setter branch?

**Comment by adriancole** [comment]
@naoman just deleted it. yeah you can assume post-merge any PR branches can/should be deleted
